# action.yml
name: 'Create TEAM'
description: 'A custom GitHub Action to create Team on Terraform entreprise'
inputs:
  team_name:
    description: 'The team name to be created.'
    required: true
  tfe_token: 
    description: 'TFE token'
    required: true
runs:
  using: "composite"
  steps:
    - run: chmod 777 ./my-custom-action/create-team.sh 
      shell: bash
    - run: ./my-custom-action/create-team.sh  ${{ inputs.team_name }} ${{ inputs.tfe_token }}
      shell: bash

