name: TFE Create Terraform workspace and team
on:
  workflow_dispatch:
    inputs:
      team:
        required: true
        type: string
        description: team name
      
jobs:
  teams:
    runs-on: ubuntu-latest
    environment: LOCAL
    env: 
      TFE_ADDR: app.terraform.io 
      TFE_ORG: shb-1988
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Custom Action
        id: my-action
        uses: ./my-custom-action
        with:
          team_name: 'team4'
