
name: TFE create TEAM 
on:
  workflow_call:
    input:
      team: 
        required: true 
        type: string
        description: team name 
jobs:
  teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Custom Action
        id: my-action
        uses: ./my-custom-action
        with:
          team_name: 'team4'
